### ISSUE TITLE
GOT ERROR while running SPIDEr Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.semgraph.semgrex.SemgrexPattern

### ISSUE THREAD

**Issue by sharadchandakacherla** [Labbeti/aac-metrics#7]
I was trying to run SPIDEr metric on one of my tasks, which is a combination of SPICE and CIDEr. CIDEr works fine. I checked my ~/.cache/aac-metrics dir for the packages. The class is present in edu/stanford/nlp/semgraph/semgrex/SemgrexPattern 
Is there any issue in passing this to the classpath of SPICE during runtime? is this related to https://github.com/tylin/coco-caption/issues/42 ?
I could have done something wrong , please let me know. 
**ERROR STACKTRACE**

Invalid SPICE call.
Full command: 'java -jar -Xmx8G /Users/userName/.cache/aac-metrics/spice/spice-1.0.jar /var/folders/yy/1xn9f2qd2xsgpq6rt7mm4df40000gn/T/spice_inputs_jfqgp8i3.json -cache /var/folders/yy/1xn9f2qd2xsgpq6rt7mm4df40000gn/T/tmp2rghop0y -out /var/folders/yy/1xn9f2qd2xsgpq6rt7mm4df40000gn/T/spice_outputs_h5vn2ztp.json -subset'
For more information, see temp files '/var/folders/yy/1xn9f2qd2xsgpq6rt7mm4df40000gn/T/spice_stdout_ip0y0dft.txt' and '/var/folders/yy/1xn9f2qd2xsgpq6rt7mm4df40000gn/T/spice_stderr_b3aj347v.txt'.
Content of '/var/folders/yy/1xn9f2qd2xsgpq6rt7mm4df40000gn/T/spice_stdout_ip0y0dft.txt':

Content of '/var/folders/yy/1xn9f2qd2xsgpq6rt7mm4df40000gn/T/spice_stderr_b3aj347v.txt':
Exception in thread "main" java.lang.NoClassDefFoundError: edu/stanford/nlp/semgraph/semgrex/SemgrexPattern

	at edu.anu.spice.SpiceParser.<clinit>(SpiceParser.java:64)

	at edu.anu.spice.SpiceScorer.scoreBatch(SpiceScorer.java:70)

	at edu.anu.spice.SpiceScorer.main(SpiceScorer.java:60)

Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.semgraph.semgrex.SemgrexPattern

	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)

	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

**Comment by Labbeti** [comment]
Hi!
Seems like some JAR files are missing to compute SPICE. 
I think the expected folder tree for SPICE in (~/.cache/aac-metrics) is:
```
    spice
    ├── cache
    ├── lib
    │   ├── ejml-0.23.jar
    │   ├── fst-2.47.jar
    │   ├── guava-19.0.jar
    │   ├── hamcrest-core-1.3.jar
    │   ├── jackson-core-2.5.3.jar
    │   ├── javassist-3.19.0-GA.jar
    │   ├── json-simple-1.1.1.jar
    │   ├── junit-4.12.jar
    │   ├── lmdbjni-0.4.6.jar
    │   ├── lmdbjni-linux64-0.4.6.jar
    │   ├── lmdbjni-osx64-0.4.6.jar
    │   ├── lmdbjni-win64-0.4.6.jar
    │   ├── Meteor-1.5.jar
    │   ├── objenesis-2.4.jar
    │   ├── SceneGraphParser-1.0.jar
    │   ├── slf4j-api-1.7.12.jar
    │   ├── slf4j-simple-1.7.21.jar
    │   ├── stanford-corenlp-3.6.0.jar
    │   └── stanford-corenlp-3.6.0-models.jar
    └── spice-1.0.jar
```
Can you check if all files are present?

**Comment by sharadchandakacherla** [comment]
Thanks for responding. You are right, some packages are missing, namely,
stanford-corenlp-3.6.0-models.jar 
stanford-corenlp-3.6.0.jar -> the error message says this was missing 
SceneGraphParser-1.0.jar
Meteor-1.5.jar

Just some additional info

For installation the steps i followed were :

1. pip install aac-metrics
2. aac-metrics-download 

(Running py 3.10.9)
Let me know if there's a mistake with the installation process
Thanks

**Comment by Labbeti** [comment]
You used the right commands to install, but something went wrong when installing SPICE, and I don't know what exactly. 
Could you try to remove all the files and directories with `rm -rf ~/.cache/aac-metrics/spice`, then re-run `aac-metrics-download` again and give me the output of that command?

**Comment by sharadchandakacherla** [comment]
Attaching the output
[2023-10-02 09:44:05,708][aac_metrics.download][INFO] - aac-metrics download started.
[2023-10-02 09:44:05,708][aac_metrics.download][INFO] - Stanford model file 'stanford_nlp' is already downloaded.
[2023-10-02 09:44:05,708][aac_metrics.download][INFO] - Meteor file 'meteor' is already downloaded.
[2023-10-02 09:44:05,709][aac_metrics.download][INFO] - Meteor file 'meteor_data' is already downloaded.
[2023-10-02 09:44:05,709][aac_metrics.download][INFO] - Meteor file 'meteor_data_fr' is already downloaded.
[2023-10-02 09:44:05,709][aac_metrics.download][INFO] - Meteor file 'meteor_data_de' is already downloaded.
[2023-10-02 09:44:05,709][aac_metrics.download][INFO] - Meteor file 'meteor_data_es' is already downloaded.
[2023-10-02 09:44:05,709][aac_metrics.download][INFO] - Meteor file 'meteor_data_cz' is already downloaded.
[2023-10-02 09:44:05,709][aac_metrics.download][INFO] - Downloading SPICE ZIP file '/Users/userName/.cache/aac-metrics/spice/SPICE-1.0.zip'...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29.3M/29.3M [00:00<00:00, 31.9MB/s]
[2023-10-02 09:44:07,128][aac_metrics.download][INFO] - Downloading JAR sources for SPICE metric into '/Users/userName/.cache/aac-metrics/spice'...
[2023-10-02 09:44:07,457][aac_metrics.download][INFO] - Downloading SBERT and BERT error detector for FENSE metric...
[2023-10-02 09:44:10,140][aac_metrics.download][INFO] - aac-metrics download finished.

**Comment by Labbeti** [comment]
Since there is no error message, I still can't figure it out. Are the same JAR files still missing in `~/.cache/aac-metrics/spice`?

**Comment by sharadchandakacherla** [comment]
Yes. The same file are missing again. Is there any way I can build them or just place the JARs at the right locations to make it work?
I dont know if this information would be of any help, but I'm trying to run this on an m1 mac.

**Comment by Labbeti** [comment]
I don't know if aac-metrics works on Mac, it hasn't been tested for this OS.

You can also download the files that are missing manually and put them in the folder. The ZIP files containing the lib JAR files are available here : http://nlp.stanford.edu/software/stanford-corenlp-full-2015-12-09.zip.

Maybe the unstable version of aac-metrics on dev branch could also fix this issue, since I was working on SPICE download to remove the use of external bash files.

**Comment by sharadchandakacherla** [comment]
The last comment by @Labbeti worked.
